services:
  skyvern:
    container_name: skyvern
    #image: public.ecr.aws/skyvern/skyvern:latest
    build:
      context: .
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # HTTP Routers
      - "traefik.http.routers.skyvern.entrypoints=web-external"
      - "traefik.http.routers.skyvern.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/skyvern/api`)"
      # HTTPS Routers
      - "traefik.http.routers.skyvern-secure.entrypoints=websecure-external"
      - "traefik.http.routers.skyvern-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/skyvern/api`)"
      - "traefik.http.routers.skyvern-secure.service=skyvern"
      # Network
      - "traefik.http.services.skyvern.loadbalancer.server.port=8001"
      - "traefik.docker.network=traefik-proxy"
    networks:
      - default
      - traefik-proxy
    # comment out if you want to externally call skyvern API
    ports:
      - 8001:8000
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./log:/data/log
      - ./.streamlit:/app/.streamlit
    environment:
      - DATABASE_STRING="postgresql+psycopg://skyvern:${SKYVERN_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?options=-csearch_path=skyvern"
      - BROWSER_TYPE=chromium-headful
      - ENABLE_OPENAI=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      # If you want to use other LLM provider, like azure and anthropic:
      # - ENABLE_ANTHROPIC=true
      # - LLM_KEY=ANTHROPIC_CLAUDE3_OPUS
      # - ANTHROPIC_API_KEY=<your_anthropic_key>
      # - ENABLE_AZURE=true
      # - LLM_KEY=AZURE_OPENAI
      # - AZURE_DEPLOYMENT=<your_azure_deployment>
      # - AZURE_API_KEY=<your_azure_api_key>
      # - AZURE_API_BASE=<your_azure_api_base>
      # - AZURE_API_VERSION=<your_azure_api_version>
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/app/.streamlit/secrets.toml"]
      interval: 5s
      timeout: 5s
      retries: 5

  skyvern-ui:
    container_name: skyvern-ui
    image: public.ecr.aws/skyvern/skyvern-ui:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      # HTTP Routers
      - "traefik.http.routers.skyvern-ui.entrypoints=web"
      - "traefik.http.routers.skyvern-ui.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/skyvern`) && !PathPrefix(`/skyvern/api`)"
      # HTTPS Routers
      - "traefik.http.routers.skyvern-ui-secure.entrypoints=websecure"
      - "traefik.http.routers.skyvern-ui-secure.rule=Host(`${SUBDOMAIN}.${DOMAIN}`) && PathPrefix(`/skyvern`) && !PathPrefix(`/skyvern/api`)"
      - "traefik.http.routers.skyvern-ui-secure.service=skyvern-ui"
      # Network
      - "traefik.http.services.skyvern-ui.loadbalancer.server.port=8081"
      - "traefik.http.services.skyvern-ui-secure.loadbalancer.server.port=9090"
      - "traefik.docker.network=traefik-proxy"
    networks:
      - default
      - traefik-proxy
    ports:
      - 8081:8080
      - 9090:9090
    volumes:
      - ./artifacts:/data/artifacts
      - ./videos:/data/videos
      - ./har:/data/har
      - ./.streamlit:/app/.streamlit
    environment:
    # if you want to run skyvern on a remote server,
    # you need to change the host in VITE_WSS_BASE_URL and VITE_API_BASE_URL to match your server ip
      - VITE_WSS_BASE_URL=ws://skyvern:8001/api/v1
      - VITE_API_BASE_URL=http://skyvern:8001/api/v1
    #   - VITE_SKYVERN_API_KEY=
    depends_on:
      skyvern:
        condition: service_healthy
